# Generated by Django 3.1 on 2020-08-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('asolea', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
            ],
        ),
    ]
