# Generated by Django 3.1 on 2020-08-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSide', '0006_auto_20200813_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ahas',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='alcohol',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='alergico',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='alimenticio',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ardor',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='asolea',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bcontrol',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cancer',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cardiacos',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='caseros',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cirugia',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='claustrofobia',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='clavos',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='diabetes',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dispositivo',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='embarazada',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='epilepsia',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='exfoliantes',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='expuesto',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='faciales',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fuma',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='hemofilia',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='hepatitis',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='implantes',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='medicamiento',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='menopausia',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='migrana',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pasos',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pdormir',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='peeling',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='piel',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='placa',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='reacutane',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='retin',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sinusitis',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='varices',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'nowe')], default='No', max_length=2),
        ),
    ]
